version: "3"
services:
  app:
    container_name: first_proj
    restart: always
    build: .
    ports:
      - "8080:1111"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
